### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-directions-android#9]
### New Highlights

* Initial version
* Wrapper around the HTTP API
* Draw the route on a map
* Detect when the user is off-route
* Sample TestApp

Full Change Log: https://github.com/mapbox/mapbox-directions-android/milestones/v1.0.0

Release Branch: https://github.com/mapbox/mapbox-gl-native/commits/release-v1.0.0

### The TODO list for making this happen:

- [x] Create and switch to `release-v1.0.0` branch
- [x] Change version name to `1.0.0` in [`gradle.properties`](https://github.com/mapbox/mapbox-directions-android/blob/master/directions/lib/gradle.properties)
- [x] Publish `1.0.0` artifact to Maven Central from Bitrise + [Sonatype](http://central.sonatype.org/pages/releasing-the-deployment.html). [Verify](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.mapbox.mapboxsdk%22)
- [x] Create release `v1.0.0` in GitHub
- [x] Merge `release-v1.0.0` branch back into `master`
- [x] Change version name back to SNAPSHOT to support daily development. In this case set to `1.1.0-SNAPSHOT`.
- [x] Create `v1.1.0` milestone and move open issues in GitHub
- [x] Close milestone `v1.0.0` in GitHub
- [x] Update `README.md` with new version numbers
- [ ] Tweet + blog post on https://www.mapbox.com/blog

/cc @mapbox/mobile

**Comment by bleege** [comment]
Nice!  :coffee: is a powerful substance!

**Comment by zugaldia** [comment]
Blog post is here https://www.mapbox.com/blog/android-directions-library/ and tweet is here: https://twitter.com/Mapbox/status/687650634737270784. We're official!
